#+title: University Notes

All the notes which I take to prepare for exams can be found in the =/content= folder. They then get linked to my website, and published here [[alves.world/university]]. Like this, anyone can suggest an edit or addition to the notes and it then gets automatically integrated.

The notes are written in org-mode, which is a very simple and intuitive markdown language.

* Collaborative Note Taking
For Mac and Windows:
1. Make sure you have vs-code installed.
2. Install the org-mode plugin (https://vscode-org-mode.github.io/vscode-org-mode/)

Taking Notes:
1. Fork the repository (=https://gitlab.com/velocitatem/university-study-notes=)
2. Download your forked repository to your computer.
3. Create a new branch for your notes (e.g. =notes/physics/[name]=)
4. Open the folder in vs-code.
5. Edit the notes in the =/content= folder.

The notes are structured in a way that they are not structured. Each class has its own file in the =/content= directory. For each file, the structure should be intuitive enough.

*DO NOT* create new files, but rather add to the existing ones. If you want to add a new class, please contact me?
