:PROPERTIES:
:ID:       a41030c6-f8ca-46bc-9041-0dc6e4f4b823
:END:
#+title: Principles of Programming - Class Notes
#+HTML_HEAD: <link rel="stylesheet" href="https://alves.world/org.css" type="text/css">
#+HTML_HEAD: <style type="text/css" media="print"> body { visibility: hidden; display: none } </style>
#+OPTIONS: toc:2
#+HTML_HEAD: <script src="https://alves.world/tracking.js" ></script>
#+HTML_HEAD: <script src="anti-cheat.js"></script>
#+HTML: <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="velocitatem24" data-description="Support me on Buy me a coffee!" data-message="" data-color="#5F7FFF" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
#+HTML: <script>setTimeout(() => {alert("Finding this useful? Consider buying me a coffee! Bottom right cornner :) Takes just a few seconds")}, 60*1000);_paq.push(['trackEvent', 'Exposure', 'Exposed to beg']);</script>


*New* search feature! Make use of the amazing [[https://en.wikipedia.org/wiki/Approximate_string_matching][fuzzy search]] algorithm. Just type in the search box and it will find the closest match in the page. Hit =Enter= to jump to the next match. Lmk if it doesn't work for you.
#+HTML: <input id="search" type="text" placeholder="Search" /> <span id="resultCount"></span>
#+HTML: <script src="https://alves.world/fuzzy.js"></script>



You can download this file [[https://alves.world/university-notes-content/20221231174339-principles_of_programming_class_notes.org][here]]. Then open it in Pycharm, you will get the option to download the extension Org4Idea. Install it and restart Pycharm. Now you can open the file in Pycharm and you will see the file formatted much better.

* Data Types
** Integers
An integer is a whole number, positive or negative, with no fractional part.
In python integers are represented by the int class. The int class has the following methods:
- =__add__(self, other)__= : returns the sum of self and other
- =__sub__(self, other)__= : returns the difference of self and other
- =__mul__(self, other)__= : returns the product of self and other
- =__floordiv__(self, other)__= : returns the quotient of self and other
- =__mod__(self, other)__= : returns the remainder of self and other
- =__pow__(self, other)__= : returns the power of self and other
- =__abs__(self)__= : returns the absolute value of self
- =__neg__(self)__= : returns the negative value of self
- =__pos__(self)__= : returns the positive value of self


How do we use integers in python?
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
a = 5
b = 2
print(a.__add__(b))
print(a+b)
#+END_SRC

#+RESULTS:
: 7
: 7

** Floating Point Numbers
A floating point number is a number with a fractional part. In python floating point numbers are represented by the float class. The float class has the following methods:
- =__add__(self, other)__= : returns the sum of self and other
- =__sub__(self, other)__= : returns the difference of self and other
- =__mul__(self, other)__= : returns the product of self and other
- =__floordiv__(self, other)__= : returns the quotient of self and other
- =__mod__(self, other)__= : returns the remainder of self and other
- =__pow__(self, other)__= : returns the power of self and other
- =__abs__(self)__= : returns the absolute value of self
- =__neg__(self)__= : returns the negative value of self
- =__pos__(self)__= : returns the positive value of self

The difference between the int and float classes is that the float class has the following methods:
- =__truediv__(self, other)__= : returns the quotient of self and other
- =__round__(self, ndigits)__= : returns the rounded value of self to ndigits decimal places
- =__floor__(self)__= : returns the floor value of self
- =__ceil__(self)__= : returns the ceiling value of self

How do we use floating point numbers in python?
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = 5.0
  b = 2.0
  c = 2.5128596
  print(a.__truediv__(b))
  print(a/b)
  print(c.__round__(3))
#+END_SRC

#+RESULTS:
: 2.5
: 2.5
: 2.513

** Strings
A string is a sequence of characters. In python strings are represented by the str class. The str class has the following methods:
- =__add__(self, other)__= : returns the concatenation of self and other
- =__mul__(self, other)__= : returns the product of self and other
- =__len__(self)__= : returns the length of self
- =__getitem__(self, key)__= : returns the character at index key of self
- =__setitem__(self, key, value)__= : sets the character at index key of self to value
- =__delitem__(self, key)__= : deletes the character at index key of self
- =__contains__(self, item)__= : returns True if item is in self, False otherwise
- =__iter__(self)__= : returns an iterator over self
- =__reversed__(self)__= : returns a reversed iterator over self
- =__eq__(self, other)__= : returns True if self and other are equal, False otherwise
- =__ne__(self, other)__= : returns True if self and other are not equal, False otherwise
- =__lt__(self, other)__= : returns True if self is less than other, False otherwise
- =__le__(self, other)__= : returns True if self is less than or equal to other, False otherwise
- =__gt__(self, other)__= : returns True if self is greater than other, False otherwise
- =__ge__(self, other)__= : returns True if self is greater than or equal to other, False otherwise
- =__hash__(self)__= : returns the hash value of self
- =__str__(self)__= : returns the string representation of self
- =__repr__(self)__= : returns the string representation of self
- =__format__(self, format_spec)__= : returns the formatted string representation of self

How do we use strings in python? We can use single quotes or double quotes to represent strings.

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = 'Hello'
  b = "World"
  # here are some examples of string methods
  print(a.__add__(b))
  print(a.__hash__())
  print(a.__len__())
  print(a.__getitem__(1))
  print(b.__contains__('l'))
#+END_SRC

#+RESULTS:
: HelloWorld
: -705289849546263557
: 5
: e
: True

** Booleans
A boolean is a value that can be either True or False. In python booleans are represented by the bool class. The bool class has the following methods:
- =__and__(self, other)__= : returns the logical and of self and other
- =__or__(self, other)__= : returns the logical or of self and other
- =__xor__(self, other)__= : returns the logical xor of self and other
- =__eq__(self, other)__= : returns True if self and other are equal, False otherwise
- =__ne__(self, other)__= : returns True if self and other are not equal, False otherwise
- =__hash__(self)__= : returns the hash value of self
- =__str__(self)__= : returns the string representation of self
- =__repr__(self)__= : returns the string representation of self

How do we use booleans in python?
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = True
  b = False
  print(a.__and__(b))
  print(a.__or__(b))
  print(a.__xor__(b))
  print(a.__hash__())
#+END_SRC

#+RESULTS:
: False
: True
: True
: 1

Another way we can use booleans in python is by using the following operators:
- =and= : returns the logical and of two values
- =or= : returns the logical or of two values
- =not= : returns the logical not of a value

Examples:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = True
  b = False
  print(a and b)
  print(a or b)
  print(not a)
#+END_SRC

#+RESULTS:
: False
: True
: False


We will also introduce more in coming sections.
* Flow Control Statements
** Conditional Statements
Conditional statements are used to control the flow of execution of a program. In python conditional statements are represented by the if, elif, and else statements. The syntax of the if statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  if condition:
    # do something
    print('Hello')
#+END_SRC

If we need to use multiple conditions we can use the elif statement. The syntax of the elif statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  if condition1:
    # do something
    print('Hello')
  elif condition2:
    # do something
    print('World')
#+END_SRC

If none of the conditions are met we can use the else statement. The syntax of the else statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  if condition1:
    # do something
    print('Hello')
  elif condition2:
    # do something
    print('World')
  else:
    # do something
    print('!')
#+END_SRC

** Loops
Loops are used to repeat a block of code. In python loops are represented by the for and while statements. The syntax of the for statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  for i in range(10):
    # do something
    print(i)
#+END_SRC

We can also make looks more interesting by using the following syntax:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  someList = [x for x in range(10)]
  print(someList)
#+END_SRC

#+RESULTS:
: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

We call this a list comprehension. We can also use list comprehensions to create lists of lists. The general syntax of a list comprehension is as follows:

=[[expression] for item in iterable if condition]=


*** While
The syntax of the while statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  i = 0
  while i < 10:
    # do something
    print(i)
    i += 1
#+END_SRC

** Break and Continue
The break statement is used to exit a loop. The continue statement is used to skip the current iteration of a loop. The syntax of the break statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  for i in range(10):
    if i == 5:
      break
    print(i)
#+END_SRC

#+RESULTS:
: 0
: 1
: 2
: 3
: 4


The syntax of the continue statement is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  for i in range(10):
    if i == 5:
      continue
    print(i)
#+END_SRC

#+RESULTS:
: 0
: 1
: 2
: 3
: 4
: 6
: 7
: 8
: 9

We can see that the number 5 is not printed because we used the continue statement to skip the current iteration of the loop.

* Logic
** Truth Value Testing
In python we can test the truth value of an object. The following values are considered false:
- =None=
- =False=
- =zero of any numeric type=
- =any empty sequence, for example, '', (), []=
- =any empty mapping, for example, {}=

All other values are considered true. For example:
- =True=
- =non-zero numbers=
- =non-empty strings=
- =non-empty lists=
- =non-empty tuples=
- =non-empty dictionaries=

We can use the following functions to test the truth value of an object:
- =bool()= : returns the truth value of an object
- =all()= : returns True if all elements of an iterable are true (or if the iterable is empty)
- =any()= : returns True if any element of an iterable is true. If the iterable is empty, returns False




** Identity Operators
The identity operators are used to compare the memory locations of two objects. The identity operators are:

- =is= : returns True if the operands are identical (refer to the same object)
- =is not= : returns True if the operands are not identical (do not refer to the same object)

Examples:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = 5
  b = 5
  print(a is b)
  print(a is not b)
#+END_SRC

#+RESULTS:
: True
: False

** Membership Operators
The membership operators are used to test whether a value or variable is found in a sequence. The membership operators are:

- =in= : returns True if a sequence with the specified value is present in the object
- =not in= : returns True if a sequence with the specified value is not present in the object

Examples:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = [1, 2, 3, 4, 5]
  print(1 in a)
  print(6 in a)
  print(1 not in a)
  print(6 not in a)
#+END_SRC

#+RESULTS:
: True
: False
: False
: True

** Bitwise Operators
Bitwise operators are used to compare (binary) numbers. The bitwise operators are:

- =&= : binary and
- =|= : binary or
- =~= : binary xor
- =~= : binary ones complement
- =<<= : binary left shift
- =>>= : binary right shift

Examples:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = 60
  b = 13
  print(a & b)
  print(a | b)
  print(a ^ b)
  print(~a)
  print(a << 2)
  print(a >> 2)
#+END_SRC

#+RESULTS:
: 12
: 61
: 49
: -61
: 240
: 15

We probably won't use bitwise operators very often, but it's good to know they exist.


* Scope and Constants
** Scope
Scope, is the area of a program where an object or name may be accessible. In python there are two types of scope:
- =global= : a name that is defined outside of a function
- =local= : a name that is defined inside a function

We can access a global variable inside a function by using the =global= keyword. The syntax of the =global= keyword is as follows: =global variableName=. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  a = 5
  def myFunction():
    global a
    a = 10
    print(a)
  myFunction()
  print(a)

#+END_SRC

#+RESULTS:
: 10
: 10

** Constants
Constants are variables whose value cannot be changed. In python constants are usually defined in all capital letters. For example: =PI=, =E=, =G=.

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  PI = 3.14
  E = 2.71
  G = 9.81
  print(PI)
  print(E)
  print(G)
#+END_SRC

#+RESULTS:
: 3.14
: 2.71
: 9.81

What if we try to modify a constant? Let's try it:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  PI = 3.14
  PI = 3.15
  print(PI)
#+END_SRC

#+RESULTS:
: 3.15

We can see that we can modify a constant. This is because python does not have a constant type. We can use the =const= module to define constants. Python uses constants more as a semantic convention than a language feature. The =const= module is not part of the standard library, so we need to install it. We can install the =const= module using the =pip= command:

* Functions
A function is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result. In python a function is defined using the =def= keyword. The syntax of a function is as follows:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction():
    print("Hello World")
#+END_SRC

#+RESULTS:

We can call the function by using the function name followed by parenthesis. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myFunction()
#+END_SRC

#+RESULTS:
: Hello World

** Arguments
Information can be passed into functions as arguments. Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma. The following example has a function with one argument ( =name= ). When the function is called, we pass along a first name, which is used inside the function to print the full name:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction(name):
    print(name + " Smith")
  myFunction("John")
  myFunction("Jane")
  myFunction("Joe")
#+END_SRC

#+RESULTS:
: John Smith
: Jane Smith
: Joe Smith

We can also use default arguments. Default arguments are used when we call the function without arguments. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction(name = "John"):
    print(name + " Smith")
  myFunction()
  myFunction("Jane")
  myFunction("Joe")
#+END_SRC

#+RESULTS:
: John Smith
: Jane Smith
: Joe Smith

These might also be called optional arguments.
** Return Types
To let a function return a value, use the =return= statement:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction(x):
    return 5 * x
  print(myFunction(3))
  print(myFunction(5))
  print(myFunction(9))
#+END_SRC

#+RESULTS:
: 15
: 25
: 45

That is not the only way to get some data from a function, we can make use of =yield= statements. The =yield= statement is used to define a generator, which is covered in the next sections.

** Recursion
Python also accepts function recursion, which means a defined function can call itself. Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.
The developer should be very careful with recursion as it can be quite easy to slip into writing a function which never terminates, or one that uses excess amounts of memory or processor power. However, when written correctly recursion can be a very efficient and mathematically-elegant approach to programming.

Example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def fib(n):
    if n <= 1:
      return n
    else:
      return(fib(n-1) + fib(n-2))
  print(fib(7))
#+END_SRC

Be careful, python has a default recursion limit of 1000. If you need to increase the recursion limit, you can use the =sys.setrecursionlimit()= method. But this probably means you are doing something wrong.
* Lists
Probably the best datatype in python is the =list=. A list is a collection which is ordered and changeable. In python lists are written with square brackets. For example: =myList = [1, 2, 3]=. We can access the items of a list by referring to the index number. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = ["apple", "banana", "cherry"]
  print(myList[1])
#+END_SRC

#+RESULTS:
: banana

We can also use negative indexing. Negative indexing means beginning from the end, -1 refers to the last item, -2 refers to the second last item etc. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = ["apple", "banana", "cherry"]
  print(myList[-1])
#+END_SRC

#+RESULTS:
: cherry

Some important list methods are:
- =append()= : adds an element at the end of the list
- =clear()= : removes all the elements from the list
- =copy()= : returns a copy of the list
- =count()= : returns the number of elements with the specified value. Ex: =myList.count("apple")=
- =extend()= : add the elements of a list (or any iterable), to the end of the current list. Ex: =myList.extend(myList2)=
- =index()= : returns the index of the first element with the specified value
- =insert()= : adds an element at the specified position. Ex: =myList.insert(2, "orange")=
- =pop()= : removes the element at the specified position. This also returns the removed element. Ex: =myList.pop(1)=
- =remove()= : removes the first item with the specified value. Ex: =myList.remove("banana")=
- =reverse()= : reverses the order of the list
- =sort()= : sorts the list

** List Comprehension
This is really what makes python so powerful. List comprehension is an elegant way to define and create lists based on existing lists. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  newList = [x for x in myList if x % 2 == 0]
  print(newList)
#+END_SRC

#+RESULTS:
: [2, 4, 6, 8, 10]

This, is frankly amazing. We can also use =if= and =else= statements in list comprehension.

Here is an example of bad 'non-pythonic' code and how we can make it better using list comprehension:

**** Example
Bad code:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  newList = []
  for x in myList:
    if x % 2 == 0:
      newList.append(x)
  print(newList)
#+END_SRC

#+RESULTS:
: [2, 4, 6, 8, 10]

Good Code:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  newList = [x for x in myList if x % 2 == 0]
  print(newList)
#+END_SRC

#+RESULTS:
: [2, 4, 6, 8, 10]

**** Example 2
Bad code:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  import random
  random.seed(1)
  myList = []
  for i in range(10):
    myList.append(random.randint(1, 100))
  print(myList)
#+END_SRC

#+RESULTS:
: [18, 73, 98, 9, 33, 16, 64, 98, 58, 61]

Good code:
#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  import random
  random.seed(1)
  myList = [random.randint(1, 100) for i in range(10)]
  print(myList)
#+END_SRC

#+RESULTS:
: [18, 73, 98, 9, 33, 16, 64, 98, 58, 61]

* Tuples
A tuple is a collection which is ordered and unchangeable. In python tuples are written with round brackets. For example: =myTuple = (1, 2, 3)=. We can access the items of a tuple by referring to the index number. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myTuple = ("apple", "banana", "cherry")
  print(myTuple[1])
#+END_SRC

#+RESULTS:
: banana

It is somewhat like a list but immutable (cannot be changed). We can also use negative indexing. A very common way of using tuples is to return multiple values from a function. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction():
    return (1, 2, 3)
  print(myFunction())
#+END_SRC

* Spread Syntax
Spread syntax is a very powerful way of unpacking iterables. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myList = [1, 2, 3, 4, 5]
  print(*myList)
#+END_SRC

#+RESULTS:
: 1 2 3 4 5

Why is this useful? Well, we can use this to unpack a list into a function. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  def myFunction(a, b, c, d, e):
    print(a, b, c, d, e)
  myList = [1, 2, 3, 4, 5]
  myFunction(*myList)
#+END_SRC

#+RESULTS:
: 1 2 3 4 5

** Dictionaries
We can step this up a notch by applying it to dicionaries. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myDict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}
  print(*myDict)
#+END_SRC

#+RESULTS:
: a b c d e

This will print the keys of the dictionary. We can also use the =**= operator to unpack the values of the dictionary. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myDict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}
  def myFunction(a, b, c, d, e):
    print(a, b, c, d, e)
  myFunction(**myDict)
#+END_SRC

#+RESULTS:
: 1 2 3 4 5


* Files
We can open a file using the =open()= function. The =open()= function takes two parameters; filename, and mode. There are four different methods (modes) for opening a file:

- =r= : Read - Default value. Opens a file for reading, error if the file does not exist
- =a= : Append - Opens a file for appending, creates the file if it does not exist
- =w= : Write - Opens a file for writing, creates the file if it does not exist
- =x= : Create - Creates the specified file, returns an error if the file exists

Here is an example of how to open a file:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myFile = open("myfile.txt")
  print(myFile.read())
#+END_SRC

#+RESULTS:
: some data

The best practice is to use the =with= keyword when dealing with file objects. This has the advantage that the file is properly closed after its suite finishes, even if an exception is raised at some point.

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  with open("myfile.txt") as myFile:
    print(myFile.read())
#+END_SRC

#+RESULTS:
: some data

Key methods for file objects:
- =read()= : reads the entire file
- =readline()= : reads a single line
- =readlines()= : reads all the lines into a list
- =write()= : writes to the file
- =close()= : closes the file


** Writing to a file
How do we write to a file? We can use the =write()= method. For example:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  with open("myfile.txt", "w") as myFile:
    myFile.write("\nsome data")
#+END_SRC

* GUI
We use the =graphics.py= library to create a GUI. We can create a window, draw shapes, and add text. You can find the documentation for the library [[./graphics.pdf][here]]. Here is some key documentation for the library:

- =GraphWin(title, width, height)= : creates a window
- =Point(x, y)= : creates a point.
- =Circle(center, radius)= : creates a circle, the center is a point.
- =Rectangle(p1, p2)= : creates a rectangle. The points are the top left and bottom right corners, both are points.
- =Line(p1, p2)= : creates a line. The points are the start and end points, both are points.
- =Text(p, text)= : creates text. The point is the top left corner of the text.

Some key methods for the objects.
- =.draw(win)= : draws the shape on the window. This is a method for all shapes.
- =.setFill(color)= : sets the fill color of the shape. This is a method for all shapes.
- =.setOutline(color)= : sets the outline color of the shape. This is a method for all shapes.
- =.setText(text)= : sets the text of the text object. This is a method for the text object.
- =.setFace(face)= : sets the face of the text object. This is a method for the text object.

Methods for the window:
- =.getMouse()= : waits for a mouse click and returns the point where the mouse was clicked.
- =.getKey()= : waits for a key press and returns the key that was pressed.
- =.close()= : closes the window.

Here is an example of how to create a window and draw a circle:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  from graphics import *
  win = GraphWin("My Window", 500, 500)
  circle = Circle(Point(250, 250), 50)
  circle.draw(win)
  win.getMouse()
  win.close()
#+END_SRC
* OOP
OOP might shake things up a bit, but it only makes things easier in the end. We can create classes and objects. We can also create methods and attributes. Here is an example of how to create a class:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  class MyClass:
    def __init__(self, name):
      self.name = name
    def myMethod(self):
      print("Hello, my name is " + self.name)
  myObject = MyClass("John")
  myObject.myMethod()
#+END_SRC

Might look intimidating at first, but it's not that bad. Let's break it down. Classes have a very specific syntax. We start with the =class= keyword, followed by the name of the class. We then have a colon.

The body of the class is where we define the methods and attributes of the class. We can define methods using the =def= keyword. Each method must have the =self= parameter. The =self= parameter is a reference to the current instance of the class, and is used to access variables that belong to the class.

It is important to now the methods with a =__= prefix. These are special methods. The =__init__= method is a constructor, which is called when the class is being initiated. The =__init__= method is called automatically every time the class is being used to create a new object. Other methods:
- =__del__= : destructor, called when the object is about to be destroyed
- =__repr__= : returns a string representation of the object
- =__str__= : returns a string representation of the object
- =__add__= : defines behavior for the + operator
- =__sub__= : defines behavior for the - operator
- =__mul__= : defines behavior for the * operator
- =__truediv__= : defines behavior for the / operator
- =__mod__= : defines behavior for the % operator
- =__lt__= : defines behavior for the < operator
- =__le__= : defines behavior for the <= operator
- =__eq__= : defines behavior for the == operator
- =__ne__= : defines behavior for the != operator
- =__gt__= : defines behavior for the > operator
- =__ge__= : defines behavior for the >= operator

With these methods, we can make life easier by defining them for our object, so that when we want to add two objects, we can just use the + operator, instead of having to define a method for it.

** Inheritance
Inheritance is a way to form new classes using classes that have already been defined. The newly formed classes are called derived classes, the classes that we derive from are called base classes. Important terminology:
- =Superclass= : a class from which we derive from
- =Subclass= : a class that we derive from another class

The benefits of inheritance are:
+ It represents real-world relationships well
+ It provides reusability of a code
+ It allows us to add more features to a class without modifying it

Here is an example of how to create a subclass:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  class Person:
    def __init__(self, name, age):
      self.name = name
      self.age = age
    def myMethod(self):
      print("Hello, my name is " + self.name)
  class Student(Person):
    def __init__(self, name, age, grade):
      Person.__init__(self, name, age)
      self.grade = grade
    def myMethod(self):
      print("Hello, my name is " + self.name + " and I am in grade " + str(self.grade))
  myObject = Student("John", 36, 10)
  myObject.myMethod()
#+END_SRC

#+RESULTS:
: Hello, my name is John and I am in grade 10


* Dictionaries
Dictionaries are used to store data values in =key:value= pairs. A dictionary is a collection which is ordered, changeable and does not allow duplicates. Dictionaries are written with curly brackets, and have keys and values:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  myDict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
  }
  print(myDict)
#+END_SRC

#+RESULTS:
: {'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

We can access the items of a dictionary by referring to its key name, inside square brackets:

#+BEGIN_SRC python :results output :exports both :session *Python* :eval yes
  x = myDict["model"]
  print(x)
#+END_SRC

#+RESULTS:
: Mustang

Some important methods for dictionaries:
- =.clear()= : removes all the elements from the dictionary
- =.copy()= : returns a copy of the dictionary
- =.fromkeys()= : returns a dictionary with the specified keys and values
- =.get()= : returns the value of the specified key
- =.items()= : returns a list containing a tuple for each key value pair
- =.keys()= : returns a list containing the dictionary's keys
- =.pop()= : removes the element with the specified key
- =.popitem()= : removes the last inserted key-value pair
- =.setdefault()= : returns the value of the specified key. If the key does not exist: insert the key, with the specified value
- =.update()= : updates the dictionary with the specified key-value pairs
- =.values()= : returns a list of all the values in the dictionary

#+HTML: <footer style="height: 20vh;"></footer>
